version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.6-node
    working_directory: ~/singnet/snet-cli
    environment:
      TRIGGER_BUILD_BRANCH: master
    steps:
    - run:
        name: Install tools
        command: |
          sudo apt-get update
          sudo apt-get -y install libudev-dev libusb-1.0-0-dev
    - checkout
    - run:
        name: Build snet-cli
        command: |
          ./scripts/blockchain install
          sudo pip3 install -e .
    - run:
        name: Trigger platform-pipeline build
        command: |
          if [ "$CIRCLE_BRANCH" == "$TRIGGER_BUILD_BRANCH" ]
          then
            curl -u ${CIRCLECI_PLATFORM_PIPELINE_TOKEN}: \
              -d build_parameters[CIRCLE_JOB]=build \
              -d build_parameters[PARENT_PROJECT_REPONAME]="$CIRCLE_PROJECT_REPONAME" \
              -d build_parameters[PARENT_BRANCH]="$CIRCLE_BRANCH" \
              -d build_parameters[PARENT_BUILD_URL]="$CIRCLE_BUILD_URL" \
              https://circleci.com/api/v1.1/project/github/singnet/platform-pipeline/tree/${TRIGGER_BUILD_BRANCH}
          fi
